-- Spot
CREATE TABLE IF NOT EXISTS spot (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    location VARCHAR(255) NOT NULL,
    image_url TEXT,
    region ENUM('SEOUL', 'INCHEON', 'BUSAN', 'DAEGU', 'ULSAN', 'GWANGJU', 'DAEJEON', 'GYEONGGI', 'GANGWON', 'CHUNGBUK', 'CHUNGNAM', 'GYEONGBUK', 'GYEONGNAM', 'JEONBUK', 'JEONNAM', 'JEJU', 'MULTI_REGION') NOT NULL,
    address VARCHAR(255) NOT NULL,
    lat DOUBLE NOT NULL,
    lng DOUBLE NOT NULL
);
